name: Build
on: push
jobs:
  apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        uses: kivy/buildozer-action@master
        with:
          save_buildozer_cache: true
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Nexus-AI-APK
          path: bin/*.apk
