name: Nexus Build
on: [push]
jobs:
  nexus_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: System Setup
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev python3-dev
          pip3 install --user --upgrade Cython==0.29.33 buildozer

      - name: Build Execution
        run: |
          export PATH=$PATH:~/.local/bin
          yes | buildozer -v android debug
        env:
          HOME: /home/runner

      - name: Output Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Nexus-AI-APK
          path: bin/*.apk
